### ISSUE TITLE
Documentation on https://docs.sonarqube.org/display/PLUG/SonarGo

### ISSUE THREAD

**Issue by agigleux** [SonarSource/sonar-go-archived#106]
Which version of Go runtime do we need to run SonarGo?

External Links
* https://www.sonarsource.com/products/codeanalyzers/
* https://www.sonarsource.com/products/codeanalyzers/sonargo.html
* http://redirect.sonarsource.com/plugins/go.html pointing to https://www.sonarsource.com/products/codeanalyzers/sonargo.html

**Comment by saberduck** [comment]
We should also populate README on github project page
