### ISSUE TITLE
Improve support of coverage file generated by "gogradle" Gradle plugin

### ISSUE THREAD

**Issue by agigleux** [SonarSource/sonar-go-archived#215]
https://github.com/gogradle/gogradle is temporarily copying source files into the hidden folder ".gogradle/project_gopath/src/" before executing computing the coverage. At the end the coverage file is containing paths related to .gogradle and no longer from the original directory where Gradle has been executed.
When we scan the code from the root directory containing the build.gradle and look at the coverage report content, we can't find the files specified in the coverage report because they are not indexed by the scanner and they correspond to the copy of the real files.

Workaround: define the sonar.projectBaseDir to the value of the copy in the .gogradle dir (https://github.com/SonarSource/sonar-go/blob/master/uast-generator-go/build.gradle#L7).
This is not the best because we can't get the SCM data from this .gogradle directory

**Comment by saberduck** [comment]
Related to #218
