### ISSUE TITLE
Go 'select' statement should be mapped with a proper KIND or ignored

### ISSUE THREAD

**Issue by ghost** [SonarSource/sonar-go-archived#258]
There is no way to subscribe to `select` statement, so killing the noise on such statement has to be done manually when implementing a rule, by looking at the tokens. See for instance implementation of #89 .

Two approaches are possible:

- Adding a new `SELECT` kind to the list of kinds that we are covering, therefore extending the superset of Kinds.
- Completely ignore `select` statements from go, and therefore also ignore its structure. More precisely:
  - Not mapping the `block` of its body as being of `BLOCK` kind
  - Not mapping the `case`s or `default` from the body as being of `CASE` kind.

There is also probably some inconsistencies with the current `DEFAULT_CASE`, which are today flagged as being part of a `select`, while its channel clauses, also declared with `case` are not flagged with `CASE`. See DefaultCase Validator (https://github.com/SonarSource/sonar-go/blob/master/common-rule-engine/src/main/java/org/sonar/uast/validators/DefaultCaseValidator.java#L36).

**Comment by vilchik-elena** [comment]
Closing as we changed approach for UAST
