### ISSUE TITLE
InvalidPathException when importing coverage results on windows machine

### ISSUE THREAD

**Issue by tomaxsas** [SonarSource/sonar-go-archived#308]
Hy. Trying to import covergae results from windows machine, but getting:
`java.nio.file.InvalidPathException: Illegal char <:> at index 20: C:\Users\zalent\go;C:\work\go\src\<trimmed_full_path>`
On linux works fine. maybe because i have two paths in my gopath env variable?

**Comment by saberduck** [comment]
@tomaxsas this is a bug, we fail to parse multiple directories in `GOPATH`.  As a workaround, you can try to unset the variable or set it only to the single directory while importing. Thanks for reporting it!

**Comment by tomaxsas** [comment]
Thanks. Since on CI it works, it's minor bug for me.
