### ISSUE TITLE
go test report format in Json is not supported 

### ISSUE THREAD

**Issue by ghost** [SonarSource/sonar-go-archived#334]
Seems go test -json is not supported, how could i generate a json format test report? or could this plugin change to support xml format test report. I can use go-junit-report to generate xml format report

**Comment by alban-auzeill** [comment]
SonarGo 1.0 only supports the json format. `-json` is supported since go 1.10
Which version of go do you have ? ( `go version` )
You probably have go 1.9 that display the error: `flag provided but not defined: -json`

**Comment by ghost** [comment]
@alban-auzeill you are right, I will close this issue.

**Comment by alban-auzeill** [comment]
@serenabi I updated the SonarGo [Unit Test Results Import documentation](https://docs.sonarqube.org/display/PLUG/Unit+Tests+Results+Import) to mention that `-json` is supported since go 1.10. Thanks for your feedback.
