### ISSUE TITLE
no test coverage

### ISSUE THREAD

**Issue by 030** [SonarSource/sonar-go-archived#348]
When analyzed using sonar-scanner the code coverage is 0.0% while it should be 60%. How to fix this?

**Comment by saberduck** [comment]
hello @030 ,

you will need to provide us more information about your project and the way you execute your tests and launch the analysis in order to be able to help you.

**Comment by Nerzal** [comment]
Have u tried running the following in the root of your project, prio to running the scanner?
`go test -coverprofile=coverage.out ./...`

**Comment by 030** [comment]
@Nerzal I ran a `go test ./... -cover`. I will try your suggestion.

**Comment by 030** [comment]
@Nerzal the outcome is the same. Once the command has been run I run the following sonar command:

> sonar-scanner -Dsonar.projectKey=some-project -Dsonar.sources=. -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_LOGIN_GOLANG}

**Comment by Nerzal** [comment]
@030 
My command looks like the following:

> -Dsonar.projectKey=$1 -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="$2" -Dsonar.organization=fino -Dsonar.go.coverage.reportPaths="coverage.out"  -Dsonar.exclusions="**/vendor/**,**/*_test.go,config/**,docs/**,resources/**,**/generated/**" -Dsonar.tests="." -Dsonar.test.inclusions="**/*_test.go"  -Dsonar.test.exclusions="**/vendor/**,config/**,docs/**,resources/**"

I ignore vendor, docs, resources, generated etc
Important for you is the following parameter

>  -Dsonar.go.coverage.reportPaths="coverage.out"  

I run tests using 

> go test -short -cover -v -coverprofile=coverage.out -covermode=atomic ./...

**Comment by 030** [comment]
@Nerzal after adding ```-Dsonar.go.coverage.reportPaths="coverage.out"```. It works! Thank you! 👍
