### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by Nerzal** [SonarSource/sonar-go-archived#359]
We need some Contribution Guidelines.
Additionally a little Guide/Wiki-Page explaining how/where to start would be awesome.

I'd like to contribute, but don't know where to start. 
This project needs more Love!

**Comment by saberduck** [comment]
hello @Nerzal, 

thanks for your interest, however, we currently don't have the bandwidth to accept external contributions. Project needs some bigger changes in the architecture and we are bit busy with other work. We will try to give some more love to SonarGo later this year.
