### ISSUE TITLE
Rule S3981: Collection sizes and array length comparisons should make sense

### ISSUE THREAD

**Issue by agigleux** [SonarSource/sonar-go-archived#75]
Implements [RSPEC-3981](https://jira.sonarsource.com/browse/RSPEC-3981)

**Comment by saberduck** [comment]
in Go length of array or map is obtained with expression `len(arr)` , while in Java this is done by accessing property `arr.length` or calling `.size()` method. We can imagine tagging such expression by some `SIZE` kind, but this is out of scope now.
